@transactional
被try-catch捕获的,不会触发回滚
运行时异常不需要throws
throw只能抛出运行时异常
rollbackfor 默认处理运行时异常

try catch里要达到事务效果
	- throw new RuntimeException(e);
	- TransactionInterceptor.currentTransactionStatus().setRollbackOnly();

### 3 错误添加切面

AOP 切面顺序导致事务不能正确回滚，原因是事务切面优先级最低，但如果自定义的切面优先级和它一样，则还是自定义切面在内层，这时若自定义切面没有正确抛出异常，在 catch 中吃掉了异常，此时就会出现和第二种情况类似的情况，代理类得不到异常信息，也就不会回滚。

解决方案就是在切面里面也抛出异常，或者是将自定义的切面的优先级设置为更小。但是建议使用第一种在切面中抛出异常，不过话说回来，为什么我们要为一个已经有事务管理的方法添加切面呢…… 事务方法一般在 Service 层，我们可以为 Controller 层添加切面。

### 4 @Transactional 事务默认只能加在 public 的方法上

非 public 的方法会导致事务失效。Spring 为方法创建代理，添加事务通知，前提条件是该方法是 public 的，这点需要注意的就是要么设置方法为 public，要么设置可以为非 public 的方法添加事务通知。

建议使用 public 方法而不是添加配置

```java
    @Bean
    public TransactionAttributeSource transactionAttributeSource(){
        return new AnnotationTransactionAttributeSource(false);
    }
```
https://juejin.cn/post/7023778837456486436


```java
/**  
 * 回滚  
 */  
@PostMapping("/save1")  
@Transactional(rollbackFor = Exception.class)  
public void demo1(){  
    EtlLog e = new EtlLog().builder().id(UUID.randomUUID().toString()).createDate(new Date()).updateDate(new Date()).build();  
    etlLogMapper.insert(e);  
    int a = 4/0;  
}  
/**  
 * 回滚  
 */  
@PostMapping("/save2")  
@Transactional  
public void demo2(){  
    EtlLog e = new EtlLog().builder().id(UUID.randomUUID().toString()).createDate(new Date()).updateDate(new Date()).build();  
    etlLogMapper.insert(e);  
    int a = 4/0;  
}  
  
/**  
 * 不回滚  
 */  
@PostMapping("/save3")  
@Transactional(rollbackFor = Exception.class)  
public void demo3(){  
    EtlLog e = new EtlLog().builder().id(UUID.randomUUID().toString()).createDate(new Date()).updateDate(new Date()).build();  
    etlLogMapper.insert(e);  
    try {  
        File file = new File("a.txt");  
        new FileReader(file);  
    } catch (Exception ex) {  
        System.out.println(ex.getMessage());  
    }  
}  
  
/**  
 * 也不回滚  
 */  
@PostMapping("/save4")  
@Transactional  
public void demo4(){  
    EtlLog e = new EtlLog().builder().id(UUID.randomUUID().toString()).createDate(new Date()).updateDate(new Date()).build();  
    etlLogMapper.insert(e);  
    try {  
        File file = new File("a.txt");  
        new FileReader(file);  
    } catch (Exception ex) {  
        System.out.println(ex.getMessage());  
    }  
}  
  
/**  
 * 回滚  
 * @throws FileNotFoundException  
 */@PostMapping("/save5")  
@Transactional(rollbackFor = Exception.class)  
public void demo5() throws FileNotFoundException {  
    EtlLog e = new EtlLog().builder().id(UUID.randomUUID().toString()).createDate(new Date()).updateDate(new Date()).build();  
    etlLogMapper.insert(e);  
    File file = new File("a.txt");  
    new FileReader(file);  
}  
  
/**  
 * 不回滚  
 * @throws FileNotFoundException  
 */@PostMapping("/save6")  
@Transactional  
public void demo6() throws FileNotFoundException {  
    EtlLog e = new EtlLog().builder().id(UUID.randomUUID().toString()).createDate(new Date()).updateDate(new Date()).build();  
    etlLogMapper.insert(e);  
    File file = new File("a.txt");  
    new FileReader(file);  
}
/**
* 回滚
**/
@PostMapping("/save7")  
@Transactional  
public void demo7(){  
    EtlLog e = new EtlLog().builder().id(UUID.randomUUID().toString()).createDate(new Date()).updateDate(new Date()).build();  
    etlLogMapper.insert(e);  
    try {  
        File file = new File("a.txt");  
        new FileReader(file);  
    } catch (Exception ex) {  
            throw new RuntimeException(ex);  
    }  
}
```